title: Who-I-am-in-Website-Format
author: William Lydon
Personal email: dangerkin1@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  
  At the time of writing this, I am a full time student in High School creating
  a website that could possibly used in the future. I will be including
  some of my hobbies and achievements as well as maybe some more about me
  in various blog posts.
# social links
reddit: https://www.reddit.com/user/Dangerkin # DO NOT include the @ character, or else the build will fail!
github_username:  Dangerkin # DO NOT include the @ character, or else the build will fail!
Discord: https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdiscord.gg%2FaGY6rdef7B&amp;data=04%7C01%7Cw
lydon%40ebnet.org%7C6199ae2b51344364d92b08d92dae22b9%7Ce43e2deb27ef4506820eabff7ea910d8%7C0%7C0%7C637591048642471216%7C
Unknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=e41qOUZ6072L9
1pey3zp3hS2bBv8J1Jfgst9infmgxc%3D&amp;reserved=0

show_excerpts: true # set to false to remove excerpts on the homepage
